

--- #instalando pacotes do apache
   - name: Instala dependencias
     ansible.builtin.apt:
       pkg:
       - apache2
       - ghostscript
       - libapache2-mod-php
       - php
       - php-bcmath
       - php-curl
       - php-imagick
       - php-intl
       - php-json
       - php-mbstring
       - php-mysql
       - php-xml
       - php-zip
       state: latest
       update_cache: yes #assim que instalado é atualizado
     become: yes #dando permissão de super usuário para fazer toda a instalação de pacotes e atualização

