--- #instalando, configurando acesso no banco de dados
    - name: Instala dependencias do mysql
      ansible.builtin.apt:  #gerenciamento de pacotes
        pkg: #instalando todos os pacotes necessarios
        - mysql-server 
        - python3-pymysql
        state: latest 
        update_cache: yes 
      become: yes 
    - name: Criando db #criando banco de dados com a tabela wordpress_db e realizando a conexão
      community.mysql.mysql_db:
          name: wordpress_db
          state: present #criando a tabela caso não exista
          login_unix_socket: /run/mysqld/mysqld.sock
      become: yes
    - name: criando usuário 'wordpress_user' e a senha '12345' 
      community.mysql.mysql_user: #criando um user no db
          name: wordpress_user
          password: 12345
          priv: 'wordpress_db.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER' #permissão que o usuário vai ter na tabela wordpress_db
          state: present
          login_unix_socket: /run/mysqld/mysqld.sock
          host: '{{ item }}' 
      with_items:
      - 'localhost'
      - '127.0.0.1'
      - '35.90.214.123' #máquina que está rodando o wordpress
      become: yes  
    - name: configurando db para permitir conexões na rede
      ansible.builtin.replace: 
        path: /etc/mysql/mysql.conf.d/mysqld.cnf #caminho do arquivo que será modificado
        regexp: "127.0.0.1" #localhost por
        replace: "0.0.0.0" #internet inteira
      become: yes 
      notify: # notificação que o mysql será reiniciado
        - restart mysql #nome do handler     